"""SEC Form ADV lookup — loads the pre-processed bulk ADV snapshot and
exposes fuzzy firm-name search + per-firm data retrieval.

Pure module: no Streamlit dependency. Callers (app.py) wrap load_adv_data
with @st.cache_data for session-level caching.

Data file: data/adv_current.parquet, generated by scripts/build_adv_data.py
from the SEC's bulk Form ADV dataset.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Optional

import pandas as pd
from rapidfuzz import fuzz, process, utils

DEFAULT_FEE_RATE = 0.0075  # 75 bps — industry-typical RIA fee assumption
DATA_PATH = Path(__file__).parent / "data" / "adv_current.parquet"


@dataclass(frozen=True)
class FirmMatch:
    """Lightweight search result for the firm-picker selectbox."""
    crd: int
    firm_name: str
    aum: float
    score: float  # rapidfuzz match score 0-100


@dataclass(frozen=True)
class FirmData:
    """Full per-firm record returned after the user picks a match."""
    crd: int
    firm_name: str
    aum: float
    num_clients: Optional[int]
    num_accounts: Optional[int]
    as_of_date: Optional[str]  # ISO date string from the filing
    aum_prior_year: Optional[float]

    @property
    def growth_rate(self) -> Optional[float]:
        if self.aum_prior_year and self.aum_prior_year > 0:
            return (self.aum - self.aum_prior_year) / self.aum_prior_year
        return None

    @property
    def estimated_revenue(self) -> float:
        return self.aum * DEFAULT_FEE_RATE


def load_adv_data() -> pd.DataFrame:
    """Read the bundled Parquet snapshot. Returns empty DataFrame on
    missing file so the app degrades gracefully rather than crashing."""
    if not DATA_PATH.exists():
        return pd.DataFrame(
            columns=[
                "crd", "firm_name", "aum", "num_clients",
                "num_accounts", "as_of_date", "aum_prior_year",
            ]
        )
    return pd.read_parquet(DATA_PATH)


def search_firms(query: str, df: pd.DataFrame, limit: int = 10) -> list[FirmMatch]:
    """Fuzzy-match firm names. Returns top `limit` matches sorted by score."""
    query = (query or "").strip()
    if len(query) < 3 or df.empty:
        return []

    names = df["firm_name"].tolist()
    # WRatio handles partial matches, acronyms, and word-order variation well.
    # SEC names are upper-case; default_process lowercases + strips punctuation
    # so user queries don't have to match case.
    results = process.extract(
        query, names,
        scorer=fuzz.WRatio,
        processor=utils.default_process,
        limit=limit,
    )

    matches = []
    for name, score, idx in results:
        if score < 50:  # below this, matches are noise
            continue
        row = df.iloc[idx]
        matches.append(
            FirmMatch(
                crd=int(row["crd"]),
                firm_name=str(row["firm_name"]),
                aum=float(row["aum"]) if pd.notna(row["aum"]) else 0.0,
                score=float(score),
            )
        )
    return matches


def get_firm_data(crd: int, df: pd.DataFrame) -> Optional[FirmData]:
    """Fetch full record for a CRD. Returns None if not found."""
    hit = df[df["crd"] == crd]
    if hit.empty:
        return None
    row = hit.iloc[0]

    def _opt_int(v):
        return int(v) if pd.notna(v) else None

    def _opt_float(v):
        return float(v) if pd.notna(v) else None

    def _opt_str(v):
        return str(v) if pd.notna(v) else None

    return FirmData(
        crd=int(row["crd"]),
        firm_name=str(row["firm_name"]),
        aum=float(row["aum"]) if pd.notna(row["aum"]) else 0.0,
        num_clients=_opt_int(row.get("num_clients")),
        num_accounts=_opt_int(row.get("num_accounts")),
        as_of_date=_opt_str(row.get("as_of_date")),
        aum_prior_year=_opt_float(row.get("aum_prior_year")),
    )
